import * as T from '@cloudscape-design/design-tokens';

/** 产品语义只映射官方导出，不复制色值或手写 Cloudscape 的哈希变量。 */
export const productTokens = {
  text: T.colorTextBodyDefault,
  secondary: T.colorTextBodySecondary,
  page: T.colorBackgroundLayoutMain,
  surface: T.colorBackgroundContainerContent,
  panel: T.colorBackgroundCellShaded,
  border: T.colorBorderDividerDefault,
  orange: T.colorBackgroundButtonPrimaryDefault,
  'orange-soft': T.colorBackgroundStatusWarning,
  blue: T.colorTextLinkDefault,
  'help-bg': T.colorBackgroundStatusInfo,
  'help-border': T.colorBorderStatusInfo,
  'blue-soft': T.colorBackgroundItemSelected,
  hover: T.colorBackgroundDropdownItemHover,
  'stage-done': T.colorBackgroundButtonNormalActive,
  'stage-current': T.colorTextLinkDefault,
  'stage-future': T.colorBackgroundProgressBarDefault,
  'primary-text': T.colorTextButtonPrimaryDefault,
  'font-body': T.fontFamilyBase,
  'font-heading': T.fontFamilyHeading,
  'font-size-body': T.fontSizeBodyM,
  'line-height-body': T.lineHeightBodyM,
  'font-size-small': T.fontSizeBodyS,
  'line-height-small': T.lineHeightBodyS,
  'radius-container': T.borderRadiusContainer,
  'radius-item': T.borderRadiusItem,
  'space-xs': T.spaceStaticXs,
  'space-s': T.spaceStaticS,
  'space-m': T.spaceStaticM,
  'space-l': T.spaceStaticL,
  'space-xl': T.spaceStaticXl,
} as const;
