/** 固定编号；禁止按渲染顺序重排或复用已分配的编号。重复实例用上下文和页面路径区分。 */
export const CARD_REGISTRY = {
  'lead-group': { id: 1, title: '跟进档位' },
  'legacy-todo': { id: 2, title: '角色待办参考' },
  'plan-stage': { id: 3, title: '阶段预安排' },
  'plan-summary': { id: 4, title: '安排摘要' },
  'plan-email': { id: 5, title: '邮件提醒' },
  'plan-recipient': { id: 6, title: '收件人预览' },
  'plan-review': { id: 7, title: '全流程安排' },
  'task-summary': { id: 8, title: '任务摘要' },
  'task-gates': { id: 9, title: '关键节点状态' },
  'task-table': { id: 10, title: '任务安排' },
  'task-requirement': { id: 11, title: '当前生效要求' },
  'task-submission': { id: 12, title: '本次提交' },
  'task-upload': { id: 13, title: '交付文件上传' },
  'utility-account': { id: 14, title: '水电气账户' },
  'workbench-projects': { id: 15, title: '项目关注' },
  'workbench-pending': { id: 16, title: '待我处理' },
  'workbench-handoffs': { id: 17, title: '最近交接' },
  'intake-house': { id: 18, title: '房屋摘要' },
  'intake-address': { id: 19, title: '房屋地址' },
  'intake-manual': { id: 20, title: '手动填写' },
  'intake-facts': { id: 21, title: '房产字段' },
  'intake-history': { id: 22, title: '业主与交易记录' },
  'intake-settings': { id: 23, title: '项目安排' },
  'intake-deal': { id: 24, title: '交易与日期' },
  'intake-sources': { id: 25, title: '房产资料与来源' },
  'intake-start': { id: 26, title: '创建后安排' },
  'project-list': { id: 27, title: '项目列表' },
  'guest-projects': { id: 28, title: '演示项目列表' },
  'login': { id: 29, title: '登录' },
  'task-processing': { id: 30, title: '任务处理' },
  'my-task-list': { id: 32, title: '我的任务' },
  'my-review-list': { id: 33, title: '待我审核' },
  'my-changes': { id: 34, title: '需求待确认' },
  'user-list': { id: 35, title: '用户管理' },
  'analysis-empty': { id: 36, title: '交易分析' },
  'analysis-inputs': { id: 37, title: '分析参数' },
  'analysis-purchase': { id: 38, title: '买入成本' },
  'analysis-holding': { id: 39, title: '持有成本' },
  'analysis-rehab': { id: 40, title: '装修明细' },
  'analysis-selling': { id: 41, title: '卖出成本' },
  'analysis-price': { id: 42, title: '售价' },
  'analysis-offer': { id: 43, title: '最高出价' },
  'analysis-costs': { id: 44, title: '成本结构' },
  'budget-summary': { id: 45, title: '预算汇总' },
  'budget-actual': { id: 46, title: '预算与实际' },
  'budget-lines': { id: 47, title: '预算项' },
  'budget-expenses': { id: 48, title: '支出' },
  'procurement-summary': { id: 49, title: '采购汇总' },
  'procurement-items': { id: 50, title: '采购明细' },
  'property-data': { id: 51, title: '房产结构与地块' },
  'property-utilities': { id: 52, title: '水电气账户' },
  'property-owner': { id: 53, title: '业主信息' },
  'property-mortgages': { id: 54, title: '当前按揭' },
  'property-sales': { id: 55, title: '成交史' },
  'files-upload': { id: 56, title: '上传文件' },
  'files-list': { id: 57, title: '文件列表' },
  'project-evidence': { id: 58, title: '关键节点与证据' },
  'project-inspections': { id: 59, title: '检查记录' },
  'project-budget': { id: 60, title: '预算偏差' },
  'project-facts': { id: 61, title: '项目资料' },
  'project-risks': { id: 62, title: '风险' },
  'project-notes': { id: 63, title: '备注' },
  'project-updates': { id: 64, title: '最近更新' },
  'project-header': { id: 65, title: '项目头卡' },
  'task-history': { id: 66, title: '活动记录' },
  'history-summary': { id: 67, title: '任务摘要' },
  'history-entry': { id: 68, title: '任务处理入口' },
  'widget-attention': { id: 69, title: '需要关注' },
  'widget-money': { id: 70, title: '在建项目：花了多少（灰底 = 预算）' },
  'widget-stages': { id: 71, title: '阶段分布' },
  'widget-recent': { id: 72, title: '最近更新' },
  'widget-list': { id: 73, title: '项目列表' },
  'widget-upcoming': { id: 74, title: '未来 30 天' },
  'widget-capital': { id: 75, title: '资金占用' },
  'widget-retro': { id: 76, title: '估算准不准（已完成项目）' },
  'widget-weekly': { id: 77, title: '近 12 周支出' },
  'widget-vendors': { id: 78, title: '供应商支出前五' },
  'widget-funnel': { id: 79, title: '未购入房子的跟进档位' },
  'widget-updates': { id: 80, title: '谁更新了什么' },
  'widget-turns': { id: 81, title: '每套房轮到谁' },
  'widget-gates': { id: 82, title: '待我确认的门' },
  'widget-mytodo': { id: 83, title: '我的待办' },
  'widget-procurement': { id: 84, title: '采购订单跟进' },
  'widget-site': { id: 85, title: '施工现场' },
  'widget-utilities': { id: 86, title: '水电瓦斯与保险' },
  'widget-permits': { id: 87, title: 'permit 与检查' },
  'widget-design': { id: 88, title: '设计交付' },
  'widget-saledocs': { id: 89, title: '卖出文件' },
  'widget-boss': { id: 90, title: '老板总览' },
  'workbench-metrics': { id: 91, title: '关注指标' },
  'my-task-card': { id: 92, title: '个人任务卡' },
  'step-card': { id: 93, title: '阶段证据事项' },
  'recent-project-card': { id: 94, title: '最近项目卡' },
  'turn-project-card': { id: 95, title: '交接项目卡' },
  'dashboard-metrics': { id: 96, title: '项目指标' }
} as const;
export type CardKey = keyof typeof CARD_REGISTRY;

export function cardFeedback(key: CardKey, pathname: string, search: string, context?: string): string {
  const card = CARD_REGISTRY[key];
  return [`卡片 #${String(card.id).padStart(2, '0')} · ${card.title}`, context && `对象：${context}`, `位置：${pathname}${search}`, `组件：${key}`].filter(Boolean).join('\n');
}
