import { m as uiText } from '../i18n/core.ts';
/** 固定编号；禁止按渲染顺序重排或复用已分配的编号。重复实例用上下文和页面路径区分。 */
export const CARD_REGISTRY = {
  'lead-group': { id: 1, get title() { return uiText("cardRegistry.follow.up.stage"); } },
  'legacy-todo': { id: 2, get title() { return uiText("cardRegistry.role.task.reference"); } },
  'plan-stage': { id: 3, get title() { return uiText("cardRegistry.stage.pre.assignment"); } },
  'plan-summary': { id: 4, get title() { return uiText("projectPreplan.assignment.summary"); } },
  'plan-email': { id: 5, get title() { return uiText("projectPreplan.email.reminders"); } },
  'plan-recipient': { id: 6, get title() { return uiText("cardRegistry.recipient.preview"); } },
  'plan-review': { id: 7, get title() { return uiText("projectPreplan.full.process.assignments"); } },
  'task-summary': { id: 8, get title() { return uiText("taskSummaryPanel.task.summary"); } },
  'task-gates': { id: 9, get title() { return uiText("taskSummaryPanel.milestone.status"); } },
  'task-table': { id: 10, get title() { return uiText("taskTable.task.assignments"); } },
  'task-requirement': { id: 11, get title() { return uiText("taskWorkbench.current.requirements"); } },
  'task-submission': { id: 12, get title() { return uiText("cardRegistry.current.submission"); } },
  'task-upload': { id: 13, get title() { return uiText("cardRegistry.deliverable.upload"); } },
  'utility-account': { id: 14, get title() { return uiText("cardRegistry.utility.accounts"); } },
  'workbench-projects': { id: 15, get title() { return uiText("workbenchFocus.project.focus"); } },
  'workbench-pending': { id: 16, get title() { return uiText("workbenchFocus.needs.my.action"); } },
  'workbench-handoffs': { id: 17, get title() { return uiText("workbenchFocus.recent.handoffs"); } },
  'intake-house': { id: 18, get title() { return uiText("cardRegistry.property.summary"); } },
  'intake-address': { id: 19, get title() { return uiText("procurementItemRow.property.address"); } },
  'intake-manual': { id: 20, get title() { return uiText("cardRegistry.enter.manually"); } },
  'intake-facts': { id: 21, get title() { return uiText("cardRegistry.property.fields"); } },
  'intake-history': { id: 22, get title() { return uiText("cardRegistry.ownership.and.transaction.records"); } },
  'intake-settings': { id: 23, get title() { return uiText("cardRegistry.project.assignments"); } },
  'intake-deal': { id: 24, get title() { return uiText("cardRegistry.transaction.and.dates"); } },
  'intake-sources': { id: 25, get title() { return uiText("cardRegistry.property.data.and.sources"); } },
  'intake-start': { id: 26, get title() { return uiText("cardRegistry.assignments.after.creation"); } },
  'project-list': { id: 27, get title() { return uiText("cardRegistry.project.list"); } },
  'guest-projects': { id: 28, get title() { return uiText("cardRegistry.demo.project.list"); } },
  'login': { id: 29, get title() { return uiText("cardRegistry.sign.in"); } },
  'task-processing': { id: 30, get title() { return uiText("cardRegistry.task.actions"); } },
  'my-task-list': { id: 32, get title() { return uiText("cardRegistry.my.tasks"); } },
  'my-review-list': { id: 33, get title() { return uiText("workbenchFocus.awaiting.my.review"); } },
  'my-changes': { id: 34, get title() { return uiText("cardRegistry.requirements.needing.confirmation"); } },
  'user-list': { id: 35, get title() { return uiText("app.user.management"); } },
  'analysis-empty': { id: 36, get title() { return uiText("cardRegistry.deal.analysis"); } },
  'analysis-inputs': { id: 37, get title() { return uiText("cardRegistry.analysis.inputs"); } },
  'analysis-purchase': { id: 38, get title() { return uiText("cardRegistry.acquisition.costs"); } },
  'analysis-holding': { id: 39, get title() { return uiText("cardRegistry.holding.costs"); } },
  'analysis-rehab': { id: 40, get title() { return uiText("cardRegistry.renovation.line.items"); } },
  'analysis-selling': { id: 41, get title() { return uiText("cardRegistry.selling.costs"); } },
  'analysis-price': { id: 42, get title() { return uiText("cardRegistry.sale.price"); } },
  'analysis-offer': { id: 43, get title() { return uiText("cardRegistry.maximum.allowable.offer"); } },
  'analysis-costs': { id: 44, get title() { return uiText("cardRegistry.cost.breakdown"); } },
  'budget-summary': { id: 45, get title() { return uiText("cardRegistry.budget.summary"); } },
  'budget-actual': { id: 46, get title() { return uiText("cardRegistry.budget.vs.actual"); } },
  'budget-lines': { id: 47, get title() { return uiText("cardRegistry.budget.item"); } },
  'budget-expenses': { id: 48, get title() { return uiText("updatesList.expenses"); } },
  'procurement-summary': { id: 49, get title() { return uiText("cardRegistry.procurement.summary"); } },
  'procurement-items': { id: 50, get title() { return uiText("cardRegistry.procurement.details"); } },
  'property-data': { id: 51, get title() { return uiText("cardRegistry.building.and.parcel"); } },
  'property-utilities': { id: 52, get title() { return uiText("cardRegistry.utility.accounts"); } },
  'property-owner': { id: 53, get title() { return uiText("cardRegistry.ownership"); } },
  'property-mortgages': { id: 54, get title() { return uiText("cardRegistry.current.mortgages"); } },
  'property-sales': { id: 55, get title() { return uiText("cardRegistry.sales.history"); } },
  'files-upload': { id: 56, get title() { return uiText("cardRegistry.upload.files"); } },
  'files-list': { id: 57, get title() { return uiText("cardRegistry.file.list"); } },
  'project-evidence': { id: 58, get title() { return uiText("cardRegistry.milestones.and.evidence"); } },
  'project-inspections': { id: 59, get title() { return uiText("zoeyDesign.inspection.records"); } },
  'project-budget': { id: 60, get title() { return uiText("cardRegistry.budget.variance"); } },
  'project-facts': { id: 61, get title() { return uiText("cardRegistry.project.documents"); } },
  'project-risks': { id: 62, get title() { return uiText("cardRegistry.risk"); } },
  'project-notes': { id: 63, get title() { return uiText("inspectionsPanel.notes"); } },
  'project-updates': { id: 64, get title() { return uiText("cardRegistry.recent.updates"); } },
  'project-header': { id: 65, get title() { return uiText("cardRegistry.project.summary.card"); } },
  'task-history': { id: 66, get title() { return uiText("taskSummaryPanel.activity.history"); } },
  'history-summary': { id: 67, get title() { return uiText("taskSummaryPanel.task.summary"); } },
  'history-entry': { id: 68, get title() { return uiText("cardRegistry.task.action.entry"); } },
  'widget-attention': { id: 69, get title() { return uiText("cardRegistry.needs.attention"); } },
  'widget-money': { id: 70, get title() { return uiText("cardRegistry.active.projects.spending.gray.background.budget"); } },
  'widget-stages': { id: 71, get title() { return uiText("founderDesign.stage.distribution"); } },
  'widget-recent': { id: 72, get title() { return uiText("cardRegistry.recent.updates"); } },
  'widget-list': { id: 73, get title() { return uiText("cardRegistry.project.list"); } },
  'widget-upcoming': { id: 74, get title() { return uiText("cardRegistry.next.30.days"); } },
  'widget-capital': { id: 75, get title() { return uiText("cardRegistry.capital.committed"); } },
  'widget-retro': { id: 76, get title() { return uiText("cardRegistry.estimate.accuracy.completed.projects"); } },
  'widget-weekly': { id: 77, get title() { return uiText("cardRegistry.expenses.over.the.last.12.weeks"); } },
  'widget-vendors': { id: 78, get title() { return uiText("cardRegistry.top.five.suppliers.by.spending"); } },
  'widget-funnel': { id: 79, get title() { return uiText("cardRegistry.follow.up.stages.for.unpurchased.properties"); } },
  'widget-updates': { id: 80, get title() { return uiText("cardRegistry.who.updated.what"); } },
  'widget-turns': { id: 81, get title() { return uiText("cardRegistry.next.action.for.each.property"); } },
  'widget-gates': { id: 82, get title() { return uiText("cardRegistry.milestones.awaiting.my.confirmation"); } },
  'widget-mytodo': { id: 83, get title() { return uiText("cardRegistry.my.tasks.2"); } },
  'widget-procurement': { id: 84, get title() { return uiText("cardRegistry.procurement.order.follow.up"); } },
  'widget-site': { id: 85, get title() { return uiText("cardRegistry.construction.site"); } },
  'widget-utilities': { id: 86, get title() { return uiText("cardRegistry.utilities.and.insurance"); } },
  'widget-permits': { id: 87, get title() { return uiText("cardRegistry.permits.and.inspections"); } },
  'widget-design': { id: 88, get title() { return uiText("cardRegistry.design.deliverables"); } },
  'widget-saledocs': { id: 89, get title() { return uiText("cardRegistry.sale.documents"); } },
  'widget-boss': { id: 90, get title() { return uiText("cardRegistry.leadership.overview"); } },
  'workbench-metrics': { id: 91, get title() { return uiText("cardRegistry.attention.metrics"); } },
  'my-task-card': { id: 92, get title() { return uiText("cardRegistry.personal.task.card"); } },
  'step-card': { id: 93, get title() { return uiText("cardRegistry.stage.evidence.items"); } },
  'recent-project-card': { id: 94, get title() { return uiText("cardRegistry.recent.project.card"); } },
  'turn-project-card': { id: 95, get title() { return uiText("cardRegistry.handoff.project.card"); } },
  'dashboard-metrics': { id: 96, get title() { return uiText("cardRegistry.project.metrics"); } },
  'purchase-orders': { id: 97, get title() { return uiText("cardRegistry.purchase.orders"); } }
} as const;
export type CardKey = keyof typeof CARD_REGISTRY;

export function cardFeedback(key: CardKey, pathname: string, search: string, context?: string): string {
  const card = CARD_REGISTRY[key];
  return [uiText("sentences.card", { value1: (String(card.id).padStart(2, '0')), value2: (card.title) }), context && uiText("sentences.record", { value1: (context) }), uiText("sentences.location", { value1: (pathname), value2: (search) }), uiText("sentences.component", { value1: (key) })].filter(Boolean).join('\n');
}
